// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCl2jLzzrlp4j846Ss2CZ1lsU0_-2HQyqA',
    appId: '1:1096098840890:web:151630e66d53d84a7f5003',
    messagingSenderId: '1096098840890',
    projectId: 'agriculture-19109',
    authDomain: 'agriculture-19109.firebaseapp.com',
    storageBucket: 'agriculture-19109.appspot.com',
    measurementId: 'G-C7J2ZVYN67',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzppRNANJ6J_qZDhTzASpwnnlY4XYd4a0',
    appId: '1:1096098840890:android:29ef3ed0ffa1f00f7f5003',
    messagingSenderId: '1096098840890',
    projectId: 'agriculture-19109',
    storageBucket: 'agriculture-19109.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCx_5324eRvVRpSuwpfu6-Onn7J_jfULp8',
    appId: '1:1096098840890:ios:55dc831acfc2e0597f5003',
    messagingSenderId: '1096098840890',
    projectId: 'agriculture-19109',
    storageBucket: 'agriculture-19109.appspot.com',
    iosBundleId: 'com.example.hessenApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCx_5324eRvVRpSuwpfu6-Onn7J_jfULp8',
    appId: '1:1096098840890:ios:47f9dd1ddca5e6c87f5003',
    messagingSenderId: '1096098840890',
    projectId: 'agriculture-19109',
    storageBucket: 'agriculture-19109.appspot.com',
    iosBundleId: 'com.example.hessenApp.RunnerTests',
  );
}
